from dataclasses import dataclass
from datetime import datetime

@dataclass
class CrowdInput:
    """
    Data received by Person 3 from the previous modules.
    """

    queue_length: int
    people_arriving: int
    people_served: int
    average_service_time: float
    current_waiting_time: float
    timestamp: datetime

@dataclass
class CrowdPrediction:
    """
    Prediction generated by Person 3.
    """

    predicted_queue: int
    predicted_wait_time: float
    crowd_level: str
    congestion_risk: str
    recommended_action: str
