"""Pydantic schemas package."""

from app.schemas.facility import (
    FacilityBase,
    FacilityCreate,
    FacilityDistanceResponse,
    FacilityResponse,
    FacilityUpdate,
)
from app.schemas.department import (
    DepartmentBase,
    DepartmentCreate,
    DepartmentResponse,
)
from app.schemas.specialist import (
    SpecialistBase,
    SpecialistCreate,
    SpecialistResponse,
    SpecialistUpdate,
    DoctorScheduleUpdate,
    DoctorSlotResponse,
)
from app.schemas.diagnostic import (
    DiagnosticTestBase,
    DiagnosticTestCreate,
    DiagnosticTestResponse,
    DiagnosticTestUpdate,
    DiagnosticBookingBase,
    DiagnosticBookingCreate,
    DiagnosticBookingStatusUpdate,
    DiagnosticBookingResultStatusUpdate,
    DiagnosticBookingResponse,
    DiagnosticQueueItem,
    DiagnosticQueueSummary,
    DiagnosticQueuePositionResponse,
)
from app.schemas.medicine import (
    MedicineBase,
    MedicineCreate,
    MedicineResponse,
    MedicineUpdate,
    FacilityInventoryBase,
    FacilityInventoryCreate,
    FacilityInventoryResponse,
    FacilityInventoryUpdate,
    InventoryStockAdjustment,
    MedicineFacilityAvailabilityResponse,
)
from app.schemas.referral import (
    ReferralBase,
    ReferralCreate,
    ReferralResponse,
    ReferralStatusUpdate,
)
from app.schemas.routing import (
    FacilityRoutingRequest,
    FacilityRecommendation,
    FacilityRoutingResponse,
)
from app.schemas.operational_state import (
    CameraTelemetryPublish,
    CameraTelemetryResponse,
    FacilityOperationalState,
)
from app.schemas.appointment import (
    AppointmentBase,
    AppointmentCreate,
    AppointmentResponse,
    AppointmentStatusUpdate,
    FacilityQueueSummary,
)

__all__ = [
    "FacilityBase",
    "FacilityCreate",
    "FacilityUpdate",
    "FacilityResponse",
    "FacilityDistanceResponse",
    "DepartmentBase",
    "DepartmentCreate",
    "DepartmentResponse",
    "SpecialistBase",
    "SpecialistCreate",
    "SpecialistUpdate",
    "SpecialistResponse",
    "DoctorScheduleUpdate",
    "DoctorSlotResponse",
    "DiagnosticTestBase",
    "DiagnosticTestCreate",
    "DiagnosticTestResponse",
    "DiagnosticTestUpdate",
    "DiagnosticBookingBase",
    "DiagnosticBookingCreate",
    "DiagnosticBookingStatusUpdate",
    "DiagnosticBookingResultStatusUpdate",
    "DiagnosticBookingResponse",
    "DiagnosticQueueItem",
    "DiagnosticQueueSummary",
    "DiagnosticQueuePositionResponse",
    "MedicineBase",
    "MedicineCreate",
    "MedicineUpdate",
    "MedicineResponse",
    "FacilityInventoryBase",
    "FacilityInventoryCreate",
    "FacilityInventoryUpdate",
    "InventoryStockAdjustment",
    "FacilityInventoryResponse",
    "MedicineFacilityAvailabilityResponse",
    "ReferralBase",
    "ReferralCreate",
    "ReferralStatusUpdate",
    "ReferralResponse",
    "FacilityRoutingRequest",
    "FacilityRecommendation",
    "FacilityRoutingResponse",
    "CameraTelemetryPublish",
    "CameraTelemetryResponse",
    "FacilityOperationalState",
    "AppointmentBase",
    "AppointmentCreate",
    "AppointmentResponse",
    "AppointmentStatusUpdate",
    "FacilityQueueSummary",
]
