"""Decision engine module for Person 4.

Evaluates all candidate actions generated by scenario_generator, simulated by
scenario_simulator, and checked by fairness_engine. Ranks feasible,
fairness-satisfied scenarios and selects the optimal action recommendation
with an explainable decision rationale.
"""

from app.services.person4.models.input_models import CongestionLevel, OptimizationInput
from pydantic import BaseModel, Field
from typing import List, Optional
from app.services.person4.models.output_models import ActionType

from app.services.person4.optimizer.eta_optimizer import calculate_dynamic_eta

from app.services.person4.optimizer.fairness_engine import (
    FairnessEvaluationStatus,
    evaluate_fairness,
)

from app.services.person4.optimizer.scenario_generator import generate_scenarios

from app.services.person4.optimizer.scenario_simulator import simulate_scenario


# ============================================================
# SCORING OBJECTIVE WEIGHTS
# ============================================================

WAIT_WEIGHT: float = 0.45
QUEUE_WEIGHT: float = 0.30
RESOURCE_WEIGHT: float = 0.15
DISRUPTION_WEIGHT: float = 0.10


# Disruption penalties per action type
# 0.0 = minimal disruption
# 1.0 = maximum disruption
ACTION_DISRUPTION: dict[ActionType, float] = {
    ActionType.NO_ACTION: 0.0,
    ActionType.PRIORITY_ADJUSTMENT: 0.1,
    ActionType.REALLOCATE_RESOURCE: 0.2,
    ActionType.OPEN_COUNTER: 0.3,
}


# ============================================================
# INTERNAL DATA MODELS
# ============================================================

class EvaluatedScenario(BaseModel):
    """Container for an individually evaluated candidate scenario."""

    action: ActionType = Field(
        ...,
        description="Action type candidate",
    )

    feasible: bool = Field(
        ...,
        description="Operational feasibility flag",
    )

    predicted_wait_minutes: float = Field(
        ...,
        ge=0.0,
        description="Projected wait time in minutes",
    )

    predicted_queue_length: int = Field(
        ...,
        ge=0,
        description="Projected queue length",
    )

    predicted_utilization: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Projected utilization ratio",
    )

    fairness_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Fairness evaluation score",
    )

    fairness_constraint_satisfied: bool = Field(
        ...,
        description="Fairness constraint satisfaction flag",
    )

    score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall decision score",
    )

    rejection_reason: Optional[str] = Field(
        None,
        description="Reason if rejected due to feasibility or fairness",
    )


class DecisionResult(BaseModel):
    """Result of the Person 4 decision engine recommendation process."""

    selected_action: ActionType = Field(
        ...,
        description="Recommended ActionType",
    )

    score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall score of the selected action",
    )

    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Deterministic decision process confidence",
    )

    reason: str = Field(
        ...,
        description="Human-readable explainable decision rationale",
    )

    evaluated_scenarios: List[EvaluatedScenario] = Field(
        ...,
        description="List of all evaluated candidate scenarios",
    )


# ============================================================
# SCORING FUNCTION
# ============================================================

def _calculate_scenario_score(
    baseline_wait: float,
    baseline_queue: int,
    cand_wait: float,
    cand_queue: int,
    resource_cost: int,
    action: ActionType,
) -> float:
    """Calculate normalized score for a candidate scenario."""

    # --------------------------------------------------------
    # 1. Wait time improvement ratio
    # --------------------------------------------------------

    if baseline_wait == 0:
        wait_score = 1.0
    else:
        wait_score = min(
            1.0,
            max(
                0.0,
                (baseline_wait - cand_wait) / baseline_wait,
            ),
        )

    # --------------------------------------------------------
    # 2. Queue length improvement ratio
    # --------------------------------------------------------

    if baseline_queue == 0:
        queue_score = 1.0
    else:
        queue_score = min(
            1.0,
            max(
                0.0,
                float(baseline_queue - cand_queue)
                / float(baseline_queue),
            ),
        )

    # --------------------------------------------------------
    # 3. Resource efficiency score
    # --------------------------------------------------------

    resource_score = max(
        0.0,
        1.0 - 0.3 * float(resource_cost),
    )

    # --------------------------------------------------------
    # 4. Disruption score
    # --------------------------------------------------------

    disruption_penalty = ACTION_DISRUPTION.get(
        action,
        0.3,
    )

    disruption_score = max(
        0.0,
        1.0 - disruption_penalty,
    )

    # --------------------------------------------------------
    # Final weighted score
    # --------------------------------------------------------

    total_score = (
        WAIT_WEIGHT * wait_score
        + QUEUE_WEIGHT * queue_score
        + RESOURCE_WEIGHT * resource_score
        + DISRUPTION_WEIGHT * disruption_score
    )

    return round(
        min(1.0, max(0.0, total_score)),
        4,
    )


# ============================================================
# DECISION ENGINE
# ============================================================

def make_decision(
    input_data: OptimizationInput,
) -> DecisionResult:
    """Evaluate all candidate actions and return the optimal recommendation.

    Args:
        input_data:
            Validated OptimizationInput payload.

    Returns:
        DecisionResult containing:
        - recommended action
        - score
        - confidence
        - reason
        - evaluated scenarios

    Raises:
        TypeError:
            If input_data is not an OptimizationInput.
    """

    # --------------------------------------------------------
    # Input validation
    # --------------------------------------------------------

    if not isinstance(input_data, OptimizationInput):
        raise TypeError(
            "input_data must be an instance of OptimizationInput"
        )

    # --------------------------------------------------------
    # Generate candidate actions
    # --------------------------------------------------------

    candidate_actions = generate_scenarios(input_data)

    # --------------------------------------------------------
    # Establish NO_ACTION baseline
    # --------------------------------------------------------

    no_action_sim = simulate_scenario(
        input_data,
        ActionType.NO_ACTION,
    )

    baseline_queue = no_action_sim.predicted_queue_length
    baseline_wait = no_action_sim.predicted_wait_minutes

    prediction_confidence = (
        input_data.prediction.prediction_confidence
    )

    # --------------------------------------------------------
    # Calculate dynamic ETA
    # --------------------------------------------------------

    eta_res = calculate_dynamic_eta(
        people_ahead=input_data.current_state.queue_length,
        recent_completed_service_times=(
            input_data.current_state.completed_service_times
        ),
        active_counters=input_data.current_state.active_counters,
    )

    # --------------------------------------------------------
    # Check for priority users
    # --------------------------------------------------------

    has_priority_users = (
        input_data.priority.time_critical_users > 0
        or input_data.priority.vulnerable_users > 0
    )

    # --------------------------------------------------------
    # Evaluate all scenarios
    # --------------------------------------------------------

    evaluated_scenarios: List[EvaluatedScenario] = []

    valid_candidates: List[
        tuple[ActionType, float, int, float, str]
    ] = []

    for action in candidate_actions:

        sim_res = simulate_scenario(
            input_data,
            action,
        )

        fair_res = evaluate_fairness(
            input_data,
            action,
        )

        # ----------------------------------------------------
        # 1. Feasibility constraint
        # ----------------------------------------------------

        if not sim_res.feasible:

            rejection = (
                f"Action {action.value} is operationally "
                f"infeasible due to insufficient resources "
                f"or eligible users."
            )

            evaluated_scenarios.append(
                EvaluatedScenario(
                    action=action,
                    feasible=False,
                    predicted_wait_minutes=(
                        sim_res.predicted_wait_minutes
                    ),
                    predicted_queue_length=(
                        sim_res.predicted_queue_length
                    ),
                    predicted_utilization=(
                        sim_res.predicted_utilization
                    ),
                    fairness_score=(
                        fair_res.fairness_score
                    ),
                    fairness_constraint_satisfied=(
                        fair_res.constraint_satisfied
                    ),
                    score=0.0,
                    rejection_reason=rejection,
                )
            )

            continue

        # ----------------------------------------------------
        # 2. Fairness constraint
        # ----------------------------------------------------

        if not fair_res.constraint_satisfied:

            rejection = (
                f"Action {action.value} rejected due to "
                f"fairness violation: {fair_res.reason}"
            )

            evaluated_scenarios.append(
                EvaluatedScenario(
                    action=action,
                    feasible=True,
                    predicted_wait_minutes=(
                        sim_res.predicted_wait_minutes
                    ),
                    predicted_queue_length=(
                        sim_res.predicted_queue_length
                    ),
                    predicted_utilization=(
                        sim_res.predicted_utilization
                    ),
                    fairness_score=(
                        fair_res.fairness_score
                    ),
                    fairness_constraint_satisfied=False,
                    score=0.0,
                    rejection_reason=rejection,
                )
            )

            continue

        # ----------------------------------------------------
        # 3. Operational score
        # ----------------------------------------------------

        score = _calculate_scenario_score(
            baseline_wait=baseline_wait,
            baseline_queue=baseline_queue,
            cand_wait=sim_res.predicted_wait_minutes,
            cand_queue=sim_res.predicted_queue_length,
            resource_cost=sim_res.resource_cost,
            action=action,
        )

        evaluated_scenarios.append(
            EvaluatedScenario(
                action=action,
                feasible=True,
                predicted_wait_minutes=(
                    sim_res.predicted_wait_minutes
                ),
                predicted_queue_length=(
                    sim_res.predicted_queue_length
                ),
                predicted_utilization=(
                    sim_res.predicted_utilization
                ),
                fairness_score=(
                    fair_res.fairness_score
                ),
                fairness_constraint_satisfied=True,
                score=score,
                rejection_reason=None,
            )
        )

        disruption = ACTION_DISRUPTION.get(
            action,
            0.3,
        )

        valid_candidates.append(
            (
                action,
                score,
                sim_res.resource_cost,
                disruption,
                fair_res.reason,
            )
        )

    # --------------------------------------------------------
    # Fallback if no valid candidate survives
    # --------------------------------------------------------

    if not valid_candidates:

        return DecisionResult(
            selected_action=ActionType.NO_ACTION,
            score=0.25,
            confidence=round(
                prediction_confidence * 0.9,
                2,
            ),
            reason=(
                "All alternative interventions were infeasible "
                "or violated fairness constraints; maintaining "
                "NO_ACTION baseline."
            ),
            evaluated_scenarios=evaluated_scenarios,
        )

    # --------------------------------------------------------
    # 4. Tie-breaking and ranking
    # --------------------------------------------------------

    def sort_key(item):
        act, score, cost, disruption, _ = item

        rounded_score = round(
            score,
            4,
        )

        # Prefer alternatives over NO_ACTION when scores tie.
        no_action_penalty = (
            1 if act == ActionType.NO_ACTION else 0
        )

        return (
            -rounded_score,
            cost,
            disruption,
            no_action_penalty,
        )

    valid_candidates.sort(
        key=sort_key
    )

    (
        selected_action,
        best_score,
        best_cost,
        best_disruption,
        fairness_reason,
    ) = valid_candidates[0]

    # --------------------------------------------------------
    # Runner-up score for confidence margin
    # --------------------------------------------------------

    runner_up_score = (
        valid_candidates[1][1]
        if len(valid_candidates) > 1
        else best_score - 0.2
    )

    score_margin = max(
        0.0,
        best_score - runner_up_score,
    )

    # --------------------------------------------------------
    # 5. Deterministic confidence calculation
    # --------------------------------------------------------

    fairness_status = evaluate_fairness(
        input_data,
        selected_action,
    ).evaluation_status

    fairness_factor = (
        0.95
        if fairness_status
        == FairnessEvaluationStatus.LIMITED_DATA
        else 1.0
    )

    margin_boost = min(
        0.1,
        score_margin * 0.2,
    )

    calculated_confidence = round(
        min(
            1.0,
            max(
                0.1,
                (
                    prediction_confidence
                    + margin_boost
                )
                * fairness_factor,
            ),
        ),
        2,
    )

    # --------------------------------------------------------
    # 6. Human-readable rationale
    # --------------------------------------------------------

    selected_sim = simulate_scenario(
        input_data,
        selected_action,
    )

    # Derive congestion from the actual selected simulation.
    # This keeps the explanation consistent with the final
    # simulated impact.
    utilization = selected_sim.predicted_utilization

    if utilization <= 0.60:
        predicted_congestion = CongestionLevel.LOW

    elif utilization <= 0.80:
        predicted_congestion = CongestionLevel.MEDIUM

    elif utilization <= 0.95:
        predicted_congestion = CongestionLevel.HIGH

    else:
        predicted_congestion = CongestionLevel.CRITICAL

    # --------------------------------------------------------
    # Generate explanation for selected action
    # --------------------------------------------------------

    if selected_action == ActionType.NO_ACTION:

        reason = (
            f"Under projected "
            f"{predicted_congestion.value} queue congestion "
            f"(queue: {baseline_queue}, "
            f"wait: {baseline_wait:.1f}m, "
            f"dynamic ETA: "
            f"{eta_res.estimated_wait_minutes:.1f}m), "
            f"current counter capacity is adequate. "
            f"NO_ACTION is recommended as operational state "
            f"remains within normal operating limits."
        )

    elif selected_action == ActionType.OPEN_COUNTER:

        reason = (
            f"Projected "
            f"{predicted_congestion.value} congestion "
            f"(queue: {baseline_queue}, "
            f"wait: {baseline_wait:.1f}m, "
            f"dynamic ETA: "
            f"{eta_res.estimated_wait_minutes:.1f}m) "
            f"warrants opening 1 service counter. "
            f"This intervention is projected to reduce "
            f"wait time to "
            f"{selected_sim.predicted_wait_minutes:.1f}m "
            f"and queue length to "
            f"{selected_sim.predicted_queue_length}."
        )

        if has_priority_users:
            reason += (
                " Time-critical and vulnerable users "
                "are protected."
            )

    elif selected_action == ActionType.REALLOCATE_RESOURCE:

        reason = (
            f"Under projected "
            f"{predicted_congestion.value} congestion "
            f"(queue: {baseline_queue}, "
            f"wait: {baseline_wait:.1f}m, "
            f"dynamic ETA: "
            f"{eta_res.estimated_wait_minutes:.1f}m), "
            f"resource reallocation increases effective "
            f"capacity by 10%, reducing projected wait "
            f"time to "
            f"{selected_sim.predicted_wait_minutes:.1f}m."
        )

        if has_priority_users:
            reason += (
                " Time-critical and vulnerable priority "
                "constraints are satisfied."
            )

    elif selected_action == ActionType.PRIORITY_ADJUSTMENT:

        total_priority = (
            input_data.priority.time_critical_users
            + input_data.priority.vulnerable_users
        )

        reason = (
            f"With {total_priority} eligible priority users "
            f"({input_data.priority.time_critical_users} "
            f"time-critical, "
            f"{input_data.priority.vulnerable_users} "
            f"vulnerable) present under projected "
            f"{predicted_congestion.value} congestion, "
            f"PRIORITY_ADJUSTMENT is recommended to protect "
            f"priority queues without additional counter costs."
        )

    else:

        # Defensive fallback.
        reason = (
            f"Action {selected_action.value} was selected "
            f"based on the highest feasible operational score."
        )

    # --------------------------------------------------------
    # Final decision result
    # --------------------------------------------------------

    return DecisionResult(
        selected_action=selected_action,
        score=best_score,
        confidence=calculated_confidence,
        reason=reason,
        evaluated_scenarios=evaluated_scenarios,
    )